#!/usr/bin/env node
/**
 * Generate TypeScript declaration file for ai-design-system
 * This script dynamically extracts types from component files
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { glob } from 'glob';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const componentsDir = path.join(__dirname, '..', 'components');
const distDir = path.join(__dirname, '..', 'dist');
const dtsPath = path.join(distDir, 'index.d.ts');

/**
 * Find the matching closing token for a balanced block.
 */
function findMatchingToken(content, startIndex, openToken, closeToken) {
  let depth = 0;

  for (let index = startIndex; index < content.length; index += 1) {
    const char = content[index];

    if (char === openToken) {
      depth += 1;
    } else if (char === closeToken) {
      depth -= 1;

      if (depth === 0) {
        return index;
      }
    }
  }

  return -1;
}

/**
 * Find the end of a type alias, accounting for nested object/function types.
 */
function findTypeAliasEnd(content, startIndex) {
  let braceDepth = 0;
  let parenDepth = 0;
  let bracketDepth = 0;

  for (let index = startIndex; index < content.length; index += 1) {
    const char = content[index];

    if (char === '{') {
      braceDepth += 1;
    } else if (char === '}') {
      braceDepth -= 1;
    } else if (char === '(') {
      parenDepth += 1;
    } else if (char === ')') {
      parenDepth -= 1;
    } else if (char === '[') {
      bracketDepth += 1;
    } else if (char === ']') {
      bracketDepth -= 1;
    } else if (char === ';' && braceDepth === 0 && parenDepth === 0 && bracketDepth === 0) {
      return index;
    }
  }

  return -1;
}

/**
 * Extract exported interfaces and types from a TypeScript file.
 */
function extractTypes(filePath) {
  const content = fs.readFileSync(filePath, 'utf8');
  const types = [];
  const exportRegex = /export\s+(interface|type)\s+(\w+)/g;
  let match;

  while ((match = exportRegex.exec(content)) !== null) {
    const exportKind = match[1];
    const exportStart = match.index;

    if (exportKind === 'interface') {
      const openBraceIndex = content.indexOf('{', exportStart);
      const closeBraceIndex = findMatchingToken(content, openBraceIndex, '{', '}');

      if (openBraceIndex !== -1 && closeBraceIndex !== -1) {
        types.push(content.slice(exportStart, closeBraceIndex + 1));
      }
      continue;
    }

    const equalsIndex = content.indexOf('=', exportStart);
    const typeEndIndex = findTypeAliasEnd(content, equalsIndex + 1);

    if (equalsIndex !== -1 && typeEndIndex !== -1) {
      types.push(content.slice(exportStart, typeEndIndex + 1));
    }
  }

  return types;
}

/**
 * Extract component exports from a TypeScript file
 */
function extractComponents(filePath) {
  const content = fs.readFileSync(filePath, 'utf8');
  const components = [];
  
  // Match: export const ComponentName = ... or export function ComponentName
  const componentRegex = /export\s+(?:const|function)\s+(\w+)/g;
  let match;
  while ((match = componentRegex.exec(content)) !== null) {
    const componentName = match[1];
    // Only include components that start with uppercase (React convention)
    if (componentName[0] === componentName[0].toUpperCase()) {
      components.push(componentName);
    }
  }
  
  return components;
}

async function generateDts() {
  // Ensure dist directory exists
  if (!fs.existsSync(distDir)) {
    fs.mkdirSync(distDir, { recursive: true });
  }

  let dtsContent = `// Type definitions for ai-design-system
// Generated by scripts/generate-dts.js
// DO NOT EDIT MANUALLY - This file is auto-generated

import * as React from 'react';
import type { Node, Connection, EdgeChange, NodeChange, OnConnectStartParams } from '@xyflow/react';

`;

  const interfaceFiles = await glob('{components,lib}/**/interfaces.ts', {
    cwd: path.join(__dirname, '..'),
    absolute: true,
  });

  const sortedInterfaceFiles = interfaceFiles.sort((left, right) => {
    const leftIsFeature = left.includes(`${path.sep}features${path.sep}`);
    const rightIsFeature = right.includes(`${path.sep}features${path.sep}`);

    if (leftIsFeature !== rightIsFeature) {
      return leftIsFeature ? 1 : -1;
    }

    return left.localeCompare(right);
  });

  if (sortedInterfaceFiles.length > 0) {
    dtsContent += `// ============================================================================
// PUBLIC TYPES
// ============================================================================

`;

    for (const filePath of sortedInterfaceFiles) {
      const types = extractTypes(filePath);

      if (types.length === 0) {
        continue;
      }

      dtsContent += `// From ${path.relative(path.join(__dirname, '..'), filePath).replace(/\\/g, '/')}
`;
      dtsContent += types.join('\n\n') + '\n\n';
    }
  }

  const hookContractFiles = await glob('components/features/*/use*.d.ts', {
    cwd: path.join(__dirname, '..'),
    absolute: true,
  });

  const sortedHookContractFiles = hookContractFiles.sort((left, right) => left.localeCompare(right));

  if (sortedHookContractFiles.length > 0) {
    dtsContent += `// ============================================================================
// HOOK CONTRACTS
// ============================================================================

`;

    for (const filePath of sortedHookContractFiles) {
      const types = extractTypes(filePath);

      if (types.length === 0) {
        continue;
      }

      dtsContent += `// From ${path.relative(path.join(__dirname, '..'), filePath).replace(/\\/g, '/')}
`;
      dtsContent += types.join('\n\n') + '\n\n';
    }
  }

  const featureComponentTypeFiles = await glob('components/features/*/*.tsx', {
    cwd: path.join(__dirname, '..'),
    absolute: true,
  });

  const sortedFeatureComponentTypeFiles = featureComponentTypeFiles
    .filter((filePath) =>
      !filePath.includes('.stories.') &&
      !filePath.includes('.mock.') &&
      !filePath.includes('.test.')
    )
    .sort((left, right) => left.localeCompare(right));

  const emittedTypeNames = new Set();

  for (const filePath of sortedFeatureComponentTypeFiles) {
    const types = extractTypes(filePath).filter((typeDeclaration) => {
      const nameMatch = typeDeclaration.match(/export\s+(?:interface|type)\s+(\w+)/);

      if (!nameMatch) {
        return false;
      }

      const typeName = nameMatch[1];
      if (emittedTypeNames.has(typeName) || dtsContent.includes(`interface ${typeName}`) || dtsContent.includes(`type ${typeName}`)) {
        return false;
      }

      emittedTypeNames.add(typeName);
      return true;
    });

    if (types.length === 0) {
      continue;
    }

    dtsContent += `// From ${path.relative(path.join(__dirname, '..'), filePath).replace(/\\/g, '/')}\n`;
    dtsContent += types.join('\n\n') + '\n\n';
  }

  dtsContent += `// ============================================================================
// FEATURE COMPONENT EXPORTS
// ============================================================================

`;

  const componentFiles = await glob('components/features/*/*.tsx', {
    cwd: path.join(__dirname, '..'),
    absolute: true,
  });

  const publicComponentFiles = componentFiles
    .filter((filePath) =>
      !filePath.includes('.stories.') &&
      !filePath.includes('.mock.') &&
      !filePath.includes('.test.')
    )
    .sort((left, right) => left.localeCompare(right));

  const emittedComponents = new Set();

  for (const filePath of publicComponentFiles) {
    const relativePath = path.relative(path.join(__dirname, '..'), filePath).replace(/\\/g, '/');
    const content = fs.readFileSync(filePath, 'utf8');
    const components = extractComponents(filePath);

    const declarations = [];
    for (const componentName of components) {
      if (emittedComponents.has(componentName)) {
        continue;
      }

      const propsInterfaceName = `${componentName}Props`;
      const hasPropsInterface =
        dtsContent.includes(`interface ${propsInterfaceName}`) ||
        content.includes(`interface ${propsInterfaceName}`) ||
        content.includes(`export interface ${propsInterfaceName}`);

      declarations.push(
        hasPropsInterface
          ? `export const ${componentName}: React.FC<${propsInterfaceName}>;`
          : `export const ${componentName}: React.FC<any>;`
      );
      emittedComponents.add(componentName);
    }

    if (declarations.length > 0) {
      dtsContent += `// From ${relativePath}\n`;
      dtsContent += declarations.join('\n') + '\n\n';
    }
  }

  // Find all composite component files
  const compositeFiles = await glob('components/composites/*/*.tsx', {
    cwd: path.join(__dirname, '..'),
    absolute: true,
  });

  for (const filePath of compositeFiles) {
    if (filePath.includes('.stories.') || filePath.includes('.mock.') || filePath.includes('.test.')) {
      continue;
    }

    const content = fs.readFileSync(filePath, 'utf8');

    const types = extractTypes(filePath);
    if (types.length > 0) {
      dtsContent += `// From ${path.relative(path.join(__dirname, '..'), filePath).replace(/\\/g, '/')}\n`;
      dtsContent += types.join('\n\n') + '\n\n';
    }

    const components = extractComponents(filePath);
    for (const componentName of components) {
      const propsInterfaceName = `${componentName}Props`;
      if (content.includes(`interface ${propsInterfaceName}`) || content.includes(`export interface ${propsInterfaceName}`)) {
        dtsContent += `export const ${componentName}: React.FC<${propsInterfaceName}>;\n`;
      } else {
        dtsContent += `export const ${componentName}: React.FC<any>;\n`;
      }
    }

    dtsContent += '\n';
  }

  dtsContent += `// ============================================================================
// EXTERNAL RE-EXPORTS
// ============================================================================

`;

  // Extract external re-exports from components/index.ts
  const indexPath = path.join(componentsDir, 'index.ts');
  if (fs.existsSync(indexPath)) {
    const indexContent = fs.readFileSync(indexPath, 'utf8');
    const indexLines = indexContent.split('\n');
    for (const line of indexLines) {
      const exportMatch = line.match(/^export\s+(?:type\s+)?\{\s*([^}]+)\s*\}\s+from\s+['"]([^'"]+)['"]/);
      if (exportMatch) {
        const fromPath = exportMatch[2];
        if (!fromPath.startsWith('.')) {
          dtsContent += line + '\n';
        }
      }
    }
  }
  dtsContent += '\n';

  dtsContent += `// ============================================================================
// BLOCK COMPONENT EXPORTS (manually declared - re-exported from ./blocks)
// ============================================================================

export declare const SectionLayout: React.FC<SectionLayoutProps>;
export declare const WorkflowCanvas: React.FC<WorkflowCanvasProps>;
export declare function getLayoutedElements(nodes: any[], edges: any[]): Promise<{ nodes: any[]; edges: any[] }>;
export declare function bmcToCanvas(bmc: CompiledBmc | null, message?: string): BmcCanvasView;
export declare function addEdge(edgeParams: any, edges: any[]): any[];

// ============================================================================
// PROMPT INPUT CONTROLLER & PROVIDER EXPORTS
// ============================================================================

export interface AttachmentsContext {
  files: Array<{
    id: string;
    url?: string;
    mediaType?: string;
    filename?: string;
    [key: string]: any;
  }>;
  add: (files: File[] | FileList) => void;
  remove: (id: string) => void;
  clear: () => void;
  openFileDialog: () => void;
  fileInputRef: React.RefObject<HTMLInputElement | null>;
}

export interface TextInputContext {
  value: string;
  setInput: (v: string) => void;
  clear: () => void;
}

export interface PromptInputControllerProps {
  textInput: TextInputContext;
  attachments: AttachmentsContext;
  __registerFileInput: (
    ref: React.RefObject<HTMLInputElement | null>,
    open: () => void
  ) => void;
}

export interface PromptInputProviderProps {
  initialInput?: string;
  children?: React.ReactNode;
}

export declare const PromptInputProvider: React.FC<PromptInputProviderProps>;
export declare function usePromptInputController(): PromptInputControllerProps;
export declare function useOptionalPromptInputController(): PromptInputControllerProps | null;
export declare function usePromptInputAttachments(): AttachmentsContext;

`;

  dtsContent += `// ============================================================================
// UTILITIES
// ============================================================================

export function cn(...inputs: any[]): string;
`;

  // Write the declaration file
  fs.writeFileSync(dtsPath, dtsContent, 'utf8');

  console.log('✅ Generated index.d.ts successfully');
  console.log(`   Processed ${publicComponentFiles.length} feature component files`);
}

generateDts().catch(err => {
  console.error('❌ Failed to generate index.d.ts:', err);
  process.exit(1);
});
